services:
  app:
    build: .
    container_name: miku_app
    restart: always
    environment:
      - SITE_NAME=MikuInvidious
      - SITE_URL=http://localhost:8000
      - HTTP_PROXY=socks5://warp:1080
      - HTTPS_PROXY=socks5://warp:1080
      - REDIS_URL=redis://redis:6379
      - NO_PROXY=0
      - SERVER_PORT=8080
      - PYTHONUNBUFFERED=1
      - SITE_MODIFIED_SOURCE_CODE_URL=https://github.com/apicalshark/mikuinvidious
      - USE_CRED=false
      # Nyaa Search functionality
      - NYAA_BANGUMI=true
      # Bilibili Credentials (Optional)
      - SESSDATA=
      - BILI_JCT=
      - BUVID3=
      - BUVID4=
      - DEDEUSERID=

  caddy:
    image: caddy:alpine
    container_name: miku_caddy
    restart: always
    ports:
      - "8000:8000"
      - "443:443/tcp"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./static:/usr/share/caddy/static
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - app

  redis:
    image: redis:alpine
    container_name: miku_redis
    restart: always

volumes:
  caddy_data:
  caddy_config:
